# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50, verbose_name='symbol')),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(verbose_name='record_date')),
                ('day_open', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='open')),
                ('day_close', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='close')),
                ('day_high', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='high')),
                ('day_low', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='low')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stochastic_engine.Company')),
            ],
        ),
    ]
